### ISSUE TITLE
Trouble using the debugger in visual studio code (windows)

### ISSUE THREAD

**Issue by mrpink76** [BugDiver/gauge-ts#9]
**Describe the bug**
Tried to debug a scenario using visual studio code.

Any hints or suggestions on how I can track down the issue?

**To Reproduce**
Using Windows 10:

1. Start a command prompt (cmd.exe)
2. Create an empty directory and change directory into the newly created directory
3. From the command line, execute: gauge init ts
4. Start visual studio code and open the file "specs\example.spec"
5. Set a breakpoint on "tests\StepImplementation.ts:16"
6. Click on the button/link "Debug Scenario" located above the line "## Vowel counts in single word"

**Expected behavior**
The breakpoint set in step 5 should be hit

**Actual behavior**
No breakpoint is hit and the following text appears in the vscode output (Gauge execution) window:
```
Running tool: gauge.cmd run c:\git\gauge_test\specs\example.spec:13 --simple-console --hide-suggestion
"Windows support is not tested yet. There might be some issues."
Runner Ready for Debugging
Debugger listening on ws://127.0.0.1:65107/7fc9502e-7137-40c7-bfa8-12c0708f7132
For help, see: https://nodejs.org/en/docs/inspector
Run stopped by user.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Gauge and plugin version [run `gauge -v`]
```
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
ts (0.0.2)
```
 - Node version [run `node -v`]: v10.16.3
 - Npm version [run `npm -v`]: 6.9.0

**Comment by BugDiver** [comment]
@mrpink76 Thanks for reporting the issue. I will definitely find some time to figure out the issue.

**Comment by BugDiver** [comment]
@mrpink76 I spent some time to look into your issue. Seems like the problem is already fixed in gauge-vscode plugin and latest gauge-ts plugin. The changes are not released yet. A release is already in progress for gauge-vsocde. I'll also try to push a release soon.
Meanwhile, can you please try installing these plugins from source and see if that fixes your issue?
The install instructions can be found in READMEs of respective plugin.

**Comment by mrpink76** [comment]
Thanks for taking the time to look at the bug!

* Uninstalled and reinstalled gauge
* Installed the gauge-ts plugin from master (0.0.3)
* Installed a custom gauge-vscode from master (0.0.12)

```
c:\git\test>gauge -v
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
ts (0.0.3)
```

Unforturnately I still get a similar error

```
Running tool: gauge.cmd run c:\git\test\specs\test1\test1.spec --simple-console --hide-suggestion
Runner Ready for Debugging
Debugger listening on ws://127.0.0.1:50180/71fbaf80-96bb-4b61-a4f1-d6cf19b2af17
For help, see: https://nodejs.org/en/docs/inspector
Error: Tests failed.
```
